before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-science texlive-fonts-extra texlive-latex-recommended
  dvipng texlive-lang-cyrillic latex-beamer
script:
- make < /dev/null
- rm -rf */*.pdf
- make < /dev/null
before_deploy:
- mkdir build
- cp */*.pdf build/
deploy:
  provider: releases
  api_key:
    secure: MjmWZxGnLCMqRuvYp7xk/D3Vuvi17vG//Qjas4ps2ewdwFJZfoPdKII0zuC2IUWaRsR081Z0ChqSh+a0+txDMkkGTiZGGGhrgKefVe1yjcshPVO/2bMSy9aEv/AHAm5jMP/99cCpk1AhdxWcnrMVdAGoLlD08fS6lVhut7ZRla44PCkgTkUDVb4KboQEizPQUsQDBUqLJQKO0unuZBV9E9iQtkqdTtv14LcmbWug23h3wkitSLrYRHdvvRaIt/5gCLoDPmURdT1vfr269c7DOK3X5r0Fp03nGFtevsOcKBSw42m2wFiuBMFka2J9AEpmsRgWghVLkQGKnPcBCPTcRj9/D8Rw2Ljujs7FgCu2eMseElec4xK/vxhEDYGWzXMTeqLoHvN1JS1J8GO/m9Z+FssD2/aH5VMlV/ifoQzCaaSc8Sh34m3KSo5goV2DTx6MBjAdkAr9W/s4ISkPY4yhCNilqY/R5a7ac1PJrX/S6MJV2mmWU82Pg4pSb0HpliUP+Gw2eerz1zMVtrtMen7kBwiq3NwARN5Yr6VgTFswsLdRIzd3+rUcIauL76UuslO7pl6eyDqP+rS6RMOattY6y6InFZcrWa//dof7cHDwynJqOlUtyp1EiLO1USu0qaL9y8PT/hOG0EhHOqg8ECAePyBvW6+1dyCGLA3e8g7Lmv4=
  file_glob: true
  file: '*/*.pdf'
  on:
    repo: elsys/os-homeworks
    tags: true
